ln -s  account-closing/account_fiscal_year_closing ./
ln -s account-invoicing/account_invoice_merge ./
ln -s account-invoice-reporting/account_invoice_production_lot ./
ln -s account-invoicing/account_invoice_refund_link ./
ln -s account-financial-reporting/account_tax_balance ./
ln -s odoo-usability/pos_sale_report ./
ln -s purchase-workflow/purchase_discount ./
ln -s reporting-engine/report_xlsx ./
ln -s stock-logistics-workflow/stock_picking_filter_lot ./
ln -s stock-logistics-workflow/stock_picking_invoice_link ./
ln -s stock-logistics-workflow/stock_picking_mass_action ./
ln -s stock-logistics-workflow/stock_picking_transfer_lot_autoassign ./
ln -s stock-logistics-warehouse/stock_quant_manual_assign ./
ln -s web/web_export_view ./
ln -s website/website_cookie_notice ./
ln -s website/website_legal_page ./
ln -s web/web_widget_color ./
